SpeedTickets/SpeedTickets/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpeedTickets.Models;

namespace SpeedTickets.Controllers
{
    public class LocationsController : Controller
    {
        MovieBookingDetailsEntities dbEntities = new MovieBookingDetailsEntities();
        // GET: Locations
        public ActionResult Index()
        {
            var locationInfo = dbEntities.tblLocations.ToList();
            return View(locationInfo);
        }
        public ActionResult AddLocation()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddLocation(tblLocation locations)
        {
            dbEntities.tblLocations.Add(locations);
            dbEntities.SaveChanges();
            return View();
        }
        public ActionResult UpdateLocation(int? LocationId)
        {
            var location = dbEntities.tblLocations.Find(LocationId);
            return View(location);
        }
        public ActionResult DeleteLocation(int LocationId)
        {
            return View();
        }
    }
}

SpeedTickets/SpeedTickets/Views/Locations/AddLocation.cshtml
@model SpeedTickets.Models.tblLocation

@{
	ViewBag.Title = "AddLocation";
}

<h2 style="font-weight:bold">Add Location</h2>

<hr />

<div style="font-weight:bold">@Html.ActionLink("View Locations","Index","Locations", new { @class = "btn btn-info" })</div>

<br />

@using (Html.BeginForm())
{
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<table class="table table-hover">
					<tr>
						<td><label>Location</label></td>
						<td>@Html.TextBoxFor(obj => obj.Location)</td>
					</tr>
				</table>
			</div>
			<input type="submit" name="name" value="Save Location" class="btn btn-success" />&ensp;
			<input type="button" name="name" value="Reset" class="btn btn-primary" />
		</div>
	</div>
}

SpeedTickets/SpeedTickets/Views/Locations/DeleteLocation.cshtml
@model SpeedTickets.Models.tblLocation
@{
	ViewBag.Title = "DeleteLocation";
}

<h2>Delete Location</h2>

SpeedTickets/SpeedTickets/Views/Locations/Index.cshtml
@model IEnumerable<SpeedTickets.Models.tblLocation>
@{
	ViewBag.Title = "Index";
}

<h2>Locations</h2>

<td>@Html.ActionLink("Add Location", "AddLocation", "Locations", new { @class = "btn btn-info" })</td>

<hr />

<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>Location Id</th>
			<th>Location</th>
			<th>Update</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
		<tr>
			<td>@Html.DisplayFor(obj => item.LocationId)</td>
			<td>@Html.DisplayFor(obj => item.Location)</td>
			<td>@Html.ActionLink("Update", "UpdateLocation",new { locationId = item.LocationId }, new { @class = "btn btn-primary" })</td>
			<td>@Html.ActionLink("Delete", "DeleteLocation", new { locationId = item.LocationId }, new { @class = "btn btn-danger" })</td>
		</tr>
		}
	</tbody>
</table>

SpeedTickets/SpeedTickets/Views/Locations/UpdateLocation.cshtml
@model SpeedTickets.Models.tblLocation
@{
	ViewBag.Title = "UpdateLocation";
}

<h2>Edit Location</h2>

<div style="font-weight:bold">Click to @Html.ActionLink("Show Locations", "Index", "Locations")</div>
<br />
@using (Html.BeginForm())
{
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<table class="table table-hover">
					<tr>
						<td><label>Location Id</label></td>
						<td>@Html.TextBoxFor(obj => obj.LocationId)</td>
					</tr>
					<tr>
						<td><label>Location</label></td>
						<td>@Html.TextBoxFor(obj => obj.Location)</td>
					</tr>
				</table>	
			</div>
			<input type="submit" name="name" value="Update Location" class="btn btn-success" />
			<input type="reset" name="name" value="Reset" class="btn btn-default" />
		</div>
	</div>
}