SpeedTickets/SpeedTickets/Controllers/TheatresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpeedTickets.Models;

namespace SpeedTickets.Controllers
{
    public class TheatresController : Controller
    {
        MovieBookingDetailsEntities dbEntities = new MovieBookingDetailsEntities();
        // GET: Theatres
        public ActionResult Index()
        {
            var theatreInfo = dbEntities.tblTheaters.ToList();
            return View(theatreInfo);
        }
        public ActionResult AddTheatre()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddTheatre(tblTheater theatres)
        {
            dbEntities.tblTheaters.Add(theatres);
            dbEntities.SaveChanges();
            return View();
        }
        public ActionResult UpdateTheatre(int? TheaterId)
        {
            var theatre = dbEntities.tblTheaters.Find(TheaterId);
            return View(theatre);
        }
        public ActionResult DeleteTheatre()
        {
            return View();
        }
    }
}

SpeedTickets/SpeedTickets/Views/Theatres/AddTheatre.cshtml
@model SpeedTickets.Models.tblTheater

@{
	ViewBag.Title = "AddTheatre";
}

<h2 style="font-weight:bold">Add Theatre</h2>

<hr />

<div style="font-weight:bold">@Html.ActionLink("View Theatres", "Index", "Theatres", new { @class = "btn btn-info" })</div>

<br />

@using (Html.BeginForm())
{
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<table class="table table-hover">
					<tr>
						<td><label>Theatre</label></td>
						<td>@Html.TextBoxFor(obj => obj.Theater)</td>
					</tr>
					<tr>
						<td><label>Theatre Type</label></td>
						<td>@Html.TextBoxFor(obj => obj.TheaterType)</td>
					</tr>
					<tr>
						<td><label>Theatre Comments</label></td>
						<td>@Html.TextBoxFor(obj => obj.Comments)</td>
					</tr>
					<tr>
						<td><label>Location Id</label></td>
						<td>@Html.TextBoxFor(obj => obj.LocationId)</td>
					</tr>
				</table>
			</div>
			<input type="submit" name="name" value="Save Theatre" class="btn btn-success" />&ensp;
			<input type="button" name="name" value="Reset" class="btn btn-primary" />
		</div>
	</div>
}

SpeedTickets/SpeedTickets/Views/Theatres/DeleteTheatre.cshtml
@model SpeedTickets.Models.tblTheater
@{
	ViewBag.Title = "DeleteTheatre";
}

<h2>Delete Theatre</h2>

SpeedTickets/SpeedTickets/Views/Theatres/Index.cshtml
@model IEnumerable<SpeedTickets.Models.tblTheater>
@{
	ViewBag.Title = "Index";
}

<h2>Theatres</h2>

<td>@Html.ActionLink("Add Theatre", "AddTheatre", "Theatres", new { @class = "btn btn-info" })</td>

<hr />

<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>Theatre Id</th>
			<th>Theatre</th>
			<th>Theatre Type</th>
			<th>Comments</th>
			<th>Location Id</th>
			<th>Update</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
		<tr>
			<td>@Html.DisplayFor(obj => item.TheaterId)</td>
			<td>@Html.DisplayFor(obj => item.Theater)</td>
			<td>@Html.DisplayFor(obj => item.TheaterType)</td>
			<td>@Html.DisplayFor(obj => item.Comments)</td>
			<td>@Html.DisplayFor(obj => item.LocationId)</td>
			<td>@Html.ActionLink("Update", "UpdateTheatre", new { id = item.TheaterId }, new { @class = "btn btn-primary" })</td>
			<td>@Html.ActionLink("Delete", "DeleteTheatre", new { id = item.TheaterId }, new { @class = "btn btn-danger" })</td>
		</tr>
		}
	</tbody>
</table>

SpeedTickets/SpeedTickets/Views/Theatres/UpdateTheatre.cshtml
@model SpeedTickets.Models.tblTheater
@{
	ViewBag.Title = "UpdateTheatre";
}

<h2>Edit Theatre</h2>

<div style="font-weight:bold">Click to @Html.ActionLink("Show Theatres", "Index", "Theatres")</div>
<br />
@using (Html.BeginForm())
{
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<table class="table table-hover">
					<tr>
						<td><label>Theater Id</label></td>
						<td>@Html.TextBoxFor(obj => obj.TheaterId)</td>
					</tr>
					<tr>
						<td><label>Theater</label></td>
						<td>@Html.TextBoxFor(obj => obj.Theater)</td>
					</tr>
					<tr>
						<td><label>Theater Type</label></td>
						<td>@Html.TextBoxFor(obj => obj.TheaterType)</td>
					</tr>
					<tr>
						<td><label>Comments</label></td>
						<td>@Html.TextBoxFor(obj => obj.Comments)</td>
					</tr>
					<tr>
						<td><label>Location Id</label></td>
						<td>@Html.TextBoxFor(obj => obj.LocationId)</td>
					</tr>
				</table>
			</div>
			<input type="submit" name="name" value="Update Theater" class="btn btn-success" />
			<input type="reset" name="name" value="Reset" class="btn btn-default" />
		</div>
	</div>
}