SpeedTickets/SpeedTickets/Controllers/LanguagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpeedTickets.Models;

namespace SpeedTickets.Controllers
{
    public class LanguagesController : Controller
    {
        MovieBookingDetailsEntities dbEntities = new MovieBookingDetailsEntities();
        // GET: Languages
        public ActionResult Index()
        {
            var languageInfo = dbEntities.tblLanguages.ToList();
            return View(languageInfo);
        }
        public ActionResult AddLanguage()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddLanguage(tblLanguage languages)
        {
            dbEntities.tblLanguages.Add(languages);
            dbEntities.SaveChanges();
            return View();
        }
        public ActionResult UpdateLanguage(int? LanguageId)
        {
            var language = dbEntities.tblLocations.Find(LanguageId);
            return View(language);
        }
        public ActionResult DeleteLanguage(int LanguageId)
        {
            return View();
        }
    }
}

SpeedTickets/SpeedTickets/Views/Languages/AddLanguage.cshtml
@model SpeedTickets.Models.tblLanguage
@{
	ViewBag.Title = "AddLanguage";
}

<h2 style="font-weight:bold">Add Language</h2>

<hr />

<div style="font-weight:bold">@Html.ActionLink("View Languages", "Index", "Languages", new { @class = "btn btn-info" })</div>

<br />

@using (Html.BeginForm())
{
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<table class="table table-hover">
					<tr>
						<td><label>Language</label></td>
						<td>@Html.TextBoxFor(obj => obj.Language)</td>
					</tr>
				</table>
			</div>
			<input type="submit" name="name" value="Save Language" class="btn btn-success" />&ensp;
			<input type="button" name="name" value="Reset" class="btn btn-primary" />
		</div>
	</div>
}

SpeedTickets/SpeedTickets/Views/Languages/DeleteLanguage.cshtml
@model SpeedTickets.Models.tblLanguage
@{
	ViewBag.Title = "DeleteLanguage";
}

<h2>Delete Language</h2>

SpeedTickets/SpeedTickets/Views/Languages/Index.cshtml
@model IEnumerable<SpeedTickets.Models.tblLanguage>
@{
	ViewBag.Title = "Index";
}

<h2>Languages</h2>

<td>@Html.ActionLink("Add Language", "AddLanguage", "Languages", new { @class = "btn btn-info" })</td>

<hr />

<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>Language Id</th>
			<th>Language</th>
			<th>Update</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>@Html.DisplayFor(obj => item.LanguageId)</td>
				<td>@Html.DisplayFor(obj => item.Language)</td>
				<td>@Html.ActionLink("Update", "UpdateLanguage", new { languageId = item.LanguageId }, new { @class = "btn btn-primary" })</td>
				<td>@Html.ActionLink("Delete", "DeleteLanguage", new { languageId = item.LanguageId }, new { @class = "btn btn-danger" })</td>
			</tr>
		}
	</tbody>
</table>

SpeedTickets/SpeedTickets/Views/Languages/UpdateLanguage.cshtml
@model SpeedTickets.Models.tblLanguage
@{
	ViewBag.Title = "UpdateLanguage";
}

<h2>Edit Language</h2>

<div style="font-weight:bold">Click to @Html.ActionLink("Show Languages", "Index", "Languages")</div>
<br />
@using (Html.BeginForm())
{
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<table class="table table-hover">
					<tr>
						<td><label>Language Id</label></td>
						<td>@Html.TextBoxFor(obj => obj.LanguageId)</td>
					</tr>
					<tr>
						<td><label>Language</label></td>
						<td>@Html.TextBoxFor(obj => obj.Language)</td>
					</tr>
				</table>
			</div>
			<input type="submit" name="name" value="Update Language" class="btn btn-success" />
			<input type="reset" name="name" value="Reset" class="btn btn-default" />
		</div>
	</div>
}